### PR TITLE
use mui appbar+toolbar for navbar. enhance link and visuals

### PR DESCRIPTION
**Pull request by jibranabsarulislam**
## Description

enhance styles visually and for accessibility

## Related Issues

#28 

## Checklist

- [ x ] I have tested my changes locally.
- [ x ] I have added necessary documentation or updated existing documentation.
- [ x ] My code follows the project's coding conventions and style guidelines.
- [ ] All tests pass successfully.
- [ ] I have added/updated relevant unit tests.

## Additional Notes

image

image

image

### CODE REVIEW

**Comment by jibranabsarulislam** [comment]
hey @Curtis-Thomas, I noticed that in the main branch there were decorators atop each function that were overwritten on merge. are these generated automatically or would you like me to add them back on this branch?

**Comment by Curtis-Thomas** [comment]
> hey @Curtis-Thomas, I noticed that in the main branch there were decorators atop each function that were overwritten on merge. are these generated automatically or would you like me to add them back on this branch?

I generated them, I will do new ones for the updated code sometime :)

**Review by Curtis-Thomas — CHANGES_REQUESTED** [review]
nav bar

Great work!

Just a  small issue with the longer names on mobile view

**Review by Curtis-Thomas — APPROVED** [review]
Perfect!

**Pull request merged**
