### PR TITLE
Enhanced Styling of BoxApiInfo Components,  fixes #65

### LINKED ISSUE #65: Enhance Styling of BoxApiInfo Component
Issue Title: Enhance Styling of BoxApiInfo Component

Issue Description:
The styling of the BoxApiInfo component can be improved to enhance its visual appeal and user experience.

Tasks:

 Review and update the Material-UI styles applied to the component.
 Adjust margins, padding, or add styling enhancements for a more polished appearance.
Acceptance Criteria:

 The component has improved Material-UI styling that enhances its visual appeal.
 The component looks more appealing and well-structured.

### PR DESCRIPTION
**Pull request by darshith-v**
## Description

Issue #65: Enhanced Styling of BoxApiInfo Component

The styling of the BoxApiInfo component are improved to enhance its visual appeal and user experience.

Reviewed and updated the Material-UI styles applied to the component.
Adjusted margins, and padding, or added styling enhancement.

## Related Issues

List any related issues or pull requests that are being addressed.

## Checklist

- [x] I have tested my changes locally.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the project's coding conventions and style guidelines.
- [x] All tests pass successfully.
- [x] I have added/updated relevant unit tests.

## Additional Notes

Include any additional notes or context about your pull request.

### CODE REVIEW

**Review by Curtis-Thomas — CHANGES_REQUESTED** [review]
Hi, good job with the changes.

Please reduce the margin bottom, it is too big and pushes the endpoints off the screen in some cases:
image

If this change is accepted the endpoint boxes will also need an adjustment to match the style. Do you think this is something you would like to do?

**Comment by darshith-v** [comment]
Good morning! Yes, I would be happy to do that!

**Review by Curtis-Thomas — COMMENTED** [review]
I still think the bottom padding is too much:

**Comment by darshith-v** [comment]
I look forward into it

**Review by Curtis-Thomas — APPROVED** [review]
Great Job!

**Comment by darshith-v** [comment]
Awesome, thanks!

**Pull request merged**
