### PR TITLE
Improved_Routing

### PR DESCRIPTION
**Pull request by pchawlaji**
## Description

1. Added an object array "routeConfig" in App.js file and removed the routes in the return. A loop will be run on the array to render the apis now.
2. Added changes in add-api.md showing how the route should be added in App.js file

## Related Issues

List any related issues or pull requests that are being addressed. https://github.com/Curtis-Thomas/free-api-list-with-react/issues/10

## Checklist

- [X] I have tested my changes locally.
- [X] I have added necessary documentation or updated existing documentation.
- [X] My code follows the project's coding conventions and style guidelines.
- [X] All tests pass successfully.
- [X] I have added/updated relevant unit tests.

## Additional Notes

I have also relocated some import statements which are standard, so that they are not lost amongst the api imports.

### CODE REVIEW

**Review by Curtis-Thomas — APPROVED** [review]
Perfect!

Great job :)

**Comment by Curtis-Thomas** [comment]
@pchawlaji there seems to be a merge conflict, I will be looking into it to try and resolve

**Comment by pchawlaji** [comment]
> @pchawlaji there seems to be a merge conflict, I will be looking into it to try and resolve

Hi @Curtis-Thomas, Good morning. I have addressed the merge conflict, whenever you have a moment kindly review.

**Review by Curtis-Thomas — APPROVED** [review]

**Comment by Curtis-Thomas** [comment]
@pchawlaji great work :)

**Comment by pchawlaji** [comment]
Thanks a lot for the kind words..!! :)

**Pull request merged**
