### PR TITLE
CardRouting component  overlaps fixed

### LINKED ISSUE #119: In the CardRouting component, When the title is a bit long it overlaps with the tags and the description
In the CardRouting component, When the title is a bit long it overlaps with the tags and the description, making it look unresponsive

Expected Behavior
All the content should be properly aligned

Steps to Reproduce (if applicable)
Checkout this temporary deployment - https://deploy-preview-117--tangerine-seahorse-5cf0e7.netlify.app/GeocodingDash for more details.

Screenshots :
Capture

Related Links
https://deploy-preview-117--tangerine-seahorse-5cf0e7.netlify.app/GeocodingDash

### PR DESCRIPTION
**Pull request by vikki9121**
## Description
hey @Curtis-Thomas 
I have completed the issue. I believe it is the better option for the website
fixed #119

before screenshot 
Screenshot 2024-01-23 215056

after solving issue #119 
Screenshot 2024-01-24 225759

### CODE REVIEW

**Comment by vikki9121** [comment]
Hey @Curtis-Thomas, is that okay?

**Comment by Curtis-Thomas** [comment]
@vikki9121 I'm away from the desk, but I will check tomorrow :)

**Comment by vikki9121** [comment]
Ok bruhh

**Review by Curtis-Thomas — CHANGES_REQUESTED** [review]
Great work, just 1 thing to be changed.

The content is now justified center which bunches the items together:

image

Could you change so the title is always at the top of the card and difficulty at the bottom?

**Comment by vikki9121** [comment]
Hey @Curtis-Thomas, I think I fixed that issue

before 
image_2024-01-26_180014932

after

**Comment by vikki9121** [comment]
@Curtis-Thomas, I think I finished both the top and bottom
image

fixed#119

**Comment by Curtis-Thomas** [comment]
> @Curtis-Thomas, I think I finished both the top and bottom image
> 
> fixed#119

hi @vikki9121 this is not showing on the current code relating to this pull request. Was it applied yet?

**Comment by vikki9121** [comment]
It was approved.

**Comment by Curtis-Thomas** [comment]
@vikki9121 could you resend in a new pull request please, this thread is giving some problems

**Pull request closed without merging**
