### PR TITLE
Update Header.js

### LINKED ISSUE #70: Improve Accessibility of Header Component
Issue Title: Improve Accessibility of Header Component

Issue Description:
Ensure that the Header component is accessible to users with disabilities and can be interacted with using a keyboard and screen reader.

Tasks:

 Add appropriate ARIA attributes and labels to the components within Header.
 Test the component's accessibility with keyboard navigation and screen reader tools.
Acceptance Criteria:

 The component is accessible to users with disabilities.
 Keyboard navigation and screen reader usage work as expected with the component.

### PR DESCRIPTION
**Pull request by eshan-one**
**Pull Request Title:**
Improve Accessibility of Header Component

**Description:**
This PR enhances the accessibility of the Header component to ensure better usability for users with disabilities. The changes include the addition of appropriate ARIA attributes, labels, and tooltips for better keyboard navigation and screen reader compatibility.

**Changes Made:**
- Added ARIA roles and labels to improve the semantic meaning of the heading.
- Included descriptive tooltips for "Tools" and "Docs" buttons to provide additional information.
- Enhanced accessibility for the "Switch" component by adding an `aria-label`.
- Tested the component's accessibility with keyboard navigation and screen reader tools.

**Related Issues:**
Closes #70

### CODE REVIEW

**Review by eshan-one — COMMENTED** [review]
Removed PropTypes

**Review by Curtis-Thomas — CHANGES_REQUESTED** [review]
Great work :)

Just a few change requests to keep codebase uniformed:

1. Change <div> for <Box>
2. Change style for sx

**Comment by eshan-one** [comment]
Alright Curtis!

**Comment by eshan-one** [comment]
Hey @Curtis-Thomas I will implement the changes for styles of sx but the first point is not clear to me which is 
1. change 
for 
Could you please explain this?

**Comment by Curtis-Thomas** [comment]
@eshan-one hi, sorry about that. Rookie error from me:

image

**Comment by eshan-one** [comment]
Alright!

**Comment by Curtis-Thomas** [comment]
I will close this pull request, please reopen in the future if you fix :)

**Comment by eshan-one** [comment]
Alright Curtis! Found it a bit difficult to fix. But will fix in the future

**Pull request closed without merging**
